language: php

php:
  - 7.2

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

env:
  - DATABASE_TEST_URL=mysql://root:@127.0.0.1/test

before_script:
  - composer install --prefer-dist --no-interaction
  - mysql_tzinfo_to_sql /usr/share/zoneinfo/Asia/Tokyo Asia/Tokyo | mysql -u root mysql
  - mysql -u root -e 'CREATE DATABASE test;'

script:
  - vendor/bin/phpunit
